import { Boom } from '@hapi/boom';
import { expandAppStateKeys } from 'whatsapp-rust-bridge';
import { proto } from '../../WAProto/index.js';
import { LabelAssociationType } from '../Types/LabelAssociation.js';
import { getBinaryNodeChild, getBinaryNodeChildren, isJidGroup, jidNormalizedUser } from '../WABinary/index.js';
import { aesDecrypt, aesEncrypt, hmacSign } from './crypto.js';
import { toNumber } from './generics.js';
import { LT_HASH_ANTI_TAMPERING } from './lt-hash.js';
import { downloadContentFromMessage } from './messages-media.js';
import { emitSyncActionResults, processContactAction } from './sync-action-utils.js';
